# Generated by Django 4.1.5 on 2024-01-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiowner',
            name='api_options_id',
            field=models.ManyToManyField(blank=True, to='chat.apioption'),
        ),
    ]
