# Generated by Django 4.1.5 on 2024-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_apiowner_api_options_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageai',
            name='text_tran',
            field=models.ManyToManyField(blank=True, to='chat.texttranmessage'),
        ),
        migrations.AlterField(
            model_name='messageuser',
            name='text_tran',
            field=models.ManyToManyField(blank=True, to='chat.texttranmessage'),
        ),
    ]
