# Generated by Django 4.1.5 on 2024-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messageai_text_tran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuserimage',
            name='text_tran',
            field=models.ManyToManyField(blank=True, to='chat.texttranmessage'),
        ),
    ]
