# Generated by Django 4.1.5 on 2024-01-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageuserimage_text_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelai',
            name='is_allow_image',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelai',
            name='is_web_search',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
