# Generated by Django 4.1.5 on 2024-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_modelai_is_allow_image_modelai_is_web_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelai',
            name='is_allow_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelai',
            name='is_web_search',
            field=models.BooleanField(default=False),
        ),
    ]
