# Generated by Django 4.1.5 on 2024-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_modelai_is_allow_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuser',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
