# Generated by Django 4.1.5 on 2024-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messageuser_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageai',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messageuser',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='texttranmessage',
            name='text',
            field=models.TextField(),
        ),
    ]
