# Generated by Django 4.1.5 on 2024-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiowner',
            name='type_service',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('research', 'Research')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('research', 'Research')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelai',
            name='type_service',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('research', 'Research')], default='text', max_length=10),
        ),
    ]
