research_prompt = {
    "en": {
        "outline": {
            1: "Generate an outline for an academic paper based on the provided topic sentence: 'Develop a detailed outline for an academic paper centered around the topic sentence: [{topic}]. Outline the main sections, subtopics, and key points to be covered in the paper.'",
            2: "Create a comprehensive outline for a research article on the given topic: 'Generate an outline for a research article focusing on [{topic}]. Structure the outline to include sections such as introduction, literature review, methodology, findings, discussion, and conclusion.'",
            3: "Outline a scholarly work on the provided topic sentence, including key sections and subheadings: 'Provide an outline for a scholarly work centered on the topic sentence: [{topic}]. Outline the major sections, subheadings, and supporting points that should be included in the work.'",
            4: "Generate an outline for a journal article exploring the given topic sentence: 'Develop an outline for a journal article that delves into [{topic}]. Outline the key sections, methodology, theoretical framework, empirical evidence, and conclusions to be included in the article.'",
            5: "Create an outline for an academic paper on the provided topic sentence, focusing on a logical flow of ideas: 'Craft an outline for an academic paper addressing [{topic}]. Structure the outline to ensure a logical flow of ideas, including an introduction, background information, main arguments, supporting evidence, and a concise conclusion.'",
        },
        "introduction": {
            1: "Craft an engaging introduction for an academic paper centered around the provided research topic: 'Develop an introduction that captures the readers’ attention and provides a concise overview of the research topic: [{topic}]. Introduce the significance, research question, and objectives of the study.'",
            2: "Write an introductory paragraph for a scholarly work exploring the given topic: 'Compose an introductory paragraph that effectively introduces the readers to the topic at hand: [{topic}]. Provide background information, context, and the rationale for the research.'",
            3: "Develop an introduction for an academic article focusing on the provided topic sentence: 'Create an introduction that sets the stage for an academic article centered around [{topic}]. Clearly state the research problem, highlight its importance, and outline the structure of the article.'",
            4: "Craft an opening paragraph for an academic paper on the given research topic: 'Write an engaging opening paragraph for an academic paper addressing [{topic}]. Use compelling language to introduce the topic, establish its relevance, and convey the research objectives.'",
            5: "Construct an introduction for a research study exploring the provided topic sentence: 'Construct an introduction that provides a comprehensive overview of the research study related to [{topic}]. Present the research gap, describe the methodology, and highlight the anticipated contributions of the study.'",
            6: "Develop an engaging introduction for a scholarly work on the given topic: 'Develop an introduction that grabs the readers’ attention and provides an overview of the scholarly work focused on [{topic}]. Present the research context, outline the key themes, and state the research objectives.'",
            7: "Write an introductory section for an academic paper exploring the provided topic sentence: 'Write an introductory section that introduces the readers to the topic described in [{topic}]. Present the research background, describe the research problem, and outline the scope and purpose of the study.'",
            8: "Craft an opening statement for an academic article centered around the given research topic: 'Craft an opening statement that effectively introduces an academic article focused on [{topic}]. Engage the readers with a thought-provoking statement and provide a brief overview of the research area.'",
            9: "Develop an introduction for an academic work that highlights the significance of the provided topic: 'Develop an introduction that emphasizes the significance and relevance of the research topic: [{topic}]. Discuss its importance in the broader context and outline the research aims and objectives.'",
            10: "Write an engaging introduction for an academic paper that sets the context for the provided research topic: 'Write an introduction that contextualizes the research topic: [{topic}]. Introduce the field of study, provide relevant background information, and articulate the research problem and objectives.'",
        },
        "review": {
            1: "Conduct a literature review on the topic of [{TOPICSENTENCE}], summarizing the key findings and insights from relevant research studies.",
            2: "Analyze and synthesize the existing literature on [{TOPICSENTENCE}], identifying the major theories, concepts, and methodologies used in previous research.",
            3: "Review a selection of scholarly articles on [{TOPICSENTENCE}], critically evaluating their methodologies, strengths, and limitations.",
            4: "Identify and discuss the key themes and trends that emerge from the literature on [{TOPICSENTENCE}], highlighting the areas of consensus and controversy.",
            5: "Conduct a systematic literature review on [{TOPICSENTENCE}], organizing and categorizing the relevant research papers based on their research questions, methodologies, and findings.",
            6: "Provide an overview of the theoretical frameworks and conceptual models that have been employed in the literature on [{TOPICSENTENCE}].",
            7: "Analyze the gaps and limitations in the existing literature on [{TOPICSENTENCE}], suggesting areas for further research and exploration.",
            8: "Compare and contrast the findings and conclusions from different research studies on [{TOPICSENTENCE}], highlighting the variations and inconsistencies.",
            9: "Examine the impact and implications of the research findings in the literature on [{TOPICSENTENCE}], considering their relevance and applicability.",
            10: "Discuss the methodological approaches used in the literature on [{TOPICSENTENCE}], evaluating their effectiveness in addressing the research questions.",
            11: "Identify the key researchers and scholars who have contributed significantly to the field of [{TOPICSENTENCE}], citing their influential works.",
            12: "Summarize and critique the methodologies employed in the literature on [{TOPICSENTENCE}], assessing their strengths and weaknesses.",
            13: "Analyze the research design and data collection methods used in the literature on [{TOPICSENTENCE}], evaluating their appropriateness and reliability.",
            14: "Provide a critical assessment of the quality and rigor of the research studies reviewed in the literature on [{TOPICSENTENCE}].",
            15: "Discuss the theoretical and practical implications of the research findings in the literature on [{TOPICSENTENCE}], considering their significance in the field.",
            16: "Synthesize the key findings and conclusions from the reviewed literature on [{TOPICSENTENCE}], highlighting the gaps and areas for future research.",
            17: "Discuss the limitations and challenges encountered in the reviewed research studies on [{TOPICSENTENCE}], suggesting strategies for improvement.",
            18: "Evaluate the credibility and relevance of the sources used in the literature on [{TOPICSENTENCE}], ensuring the inclusion of high-quality and reputable research papers.",
            19: "Provide a comprehensive bibliography of the review papers and research studies included in the literature review on [{TOPICSENTENCE}].",
            20: "Summarize the major contributions and insights from the reviewed literature on [{TOPICSENTENCE}], highlighting their significance in advancing knowledge in the field.",
        },
        "methodology": {
            1: "Design a research methodology for investigating the relationship between [variables] in the context of [{topic}].",
            2: "Develop clear research objectives and outline a comprehensive methodology to address those objectives for [{topic}].",
            3: "Write a detailed methodology section for conducting a qualitative study on [{topic}].",
            4: "Design a survey questionnaire and describe the sampling technique to be used in a quantitative research study on [{topic}].",
            5: "Discuss the strengths and limitations of using a mixed-methods approach in studying [{topic}].",
            6: "Propose a research design and methodology for conducting an experimental study on [{topic}].",
            7: "Outline a systematic review methodology for analyzing and synthesizing existing literature on [{topic}].",
            8: "Analyze the strengths and weaknesses of the chosen research methodology in investigating [{topic}].",
            9: "Develop a step-by-step procedure for collecting and analyzing primary data for [{topic}].",
            10: "Evaluate the appropriateness of using a case study methodology to explore [{topic}].",
            11: "Design a research methodology for conducting interviews with key stakeholders in the field of [{topic}].",
            12: "Discuss the ethical considerations that need to be addressed when implementing the proposed research methodology for [{topic}].",
            13: "Create a data collection plan and describe the data analysis techniques to be employed in a quantitative research study on [{topic}].",
            14: "Justify the selection of a particular research design and methodology for investigating [{topic}] based on its suitability and feasibility.",
            15: "Discuss the potential biases and limitations associated with the chosen research methodology in studying [{topic}].",
            16: "Develop a framework for analyzing qualitative data collected through interviews, focus groups, or observations for [{topic}].",
            17: "Describe the steps involved in conducting a systematic literature review as part of the research methodology for [{topic}].",
            18: "Assess the reliability and validity of the chosen measurement instruments in the research methodology for [{topic}].",
            19: "Explain how the research methodology addresses potential confounding variables and ensures internal validity in studying [{topic}].",
            20: "Compare and contrast different research methodologies (e.g., experimental, survey, case study) in terms of their suitability for investigating [{topic}].",
        },
        "discussion": {
            1: "Evaluate the significance of the study’s findings and their implications for advancing the understanding of [{topic}].",
            2: "Analyze the contributions of the current study to the existing body of knowledge on [{topic}] and highlight areas for future research.",
            3: "Discuss how the findings of the study align with or challenge existing theories and models in the field of [{topic}].",
            4: "Reflect on the methodological choices made in the study and assess their strengths and limitations in relation to the research objectives.",
            5: "Compare the results of the current study with previous research in the literature, highlighting similarities, differences, and potential reasons for discrepancies.",
            6: "Discuss any unexpected or contradictory findings and propose potential explanations or avenues for further investigation.",
            7: "Examine the practical implications of the study’s findings and discuss how they can inform decision-making or practice in [{topic}].",
            8: "Consider the generalizability of the study’s findings to other contexts or populations and discuss the potential impact on broader knowledge in [{topic}].",
            9: "Discuss the ethical considerations involved in conducting the study and their implications for the interpretation and generalizability of the findings.",
            10: "Summarize the key findings of the study, emphasizing their relevance, limitations, and implications for future research and practice in [{topic}].",
        },
        "result": {
            1: "Present and interpret the quantitative data collected in the study to provide a comprehensive analysis of the findings related to [{topic}].",
            2: "Describe the key patterns and trends observed in the qualitative data gathered during the research on [{topic}].",
            3: "Analyze the statistical significance of the results obtained from the conducted experiments on [{topic}].",
            4: "Present the survey responses and summarize the major themes and insights derived from the data in relation to [{topic}].",
            5: "Discuss the relationships and correlations found among the variables examined in the study on [{topic}].and Illustrate the main outcomes of the research through clear and concise tables,",
            6: "Interpret the findings of the data analysis and discuss their implications for the field of [{topic}].",
            7: "Illustrate the main outcomes of the research through clear and concise tables, graphs, or charts for [{topic}].",
            8: "Discuss any unexpected or contradictory results obtained during the study and propose potential explanations for them.",
            9: "Compare and contrast the findings of the current study with existing literature on [{topic}].",
            10: "Highlight the statistical significance of the observed differences or similarities between the experimental groups in the study on [{topic}].",
            11: "Summarize the qualitative responses obtained from interviews or open-ended survey questions and identify recurring themes.",
            12: "Discuss the limitations of the study in terms of potential biases or confounding factors that may have influenced the results for [{topic}].",
            13: "Provide a detailed analysis of the collected data to support the claims made in the study on [{topic}].",
            14: "Interpret the results of the statistical tests conducted to assess the hypotheses formulated for [{topic}].",
            15: "Discuss any unexpected findings or patterns that emerged from the analysis and their implications for future research.",
            16: "Present the descriptive statistics and measures of central tendency and variability for the variables examined in the study on [{topic}].",
            17: "Discuss the reliability and validity of the measurements used in the study to ensure the accuracy of the results for [{topic}].",
            18: "Summarize the key findings and their significance in addressing the research objectives of [{topic}].",
            19: "Provide a detailed analysis of any subgroups or subcategories identified within the data and their implications for [{topic}].",
            20: "Interpret the results of the data analysis in light of the research questions and objectives formulated for [{topic}].",
        },
        "summary": {
            1: "Summarize the content provided in the following paragraphs.",
            2: "Provide a concise summary of the key points discussed in the text.",
            3: "Condense the main ideas and arguments presented in the given material.",
            4: "Summarize the text, highlighting the author’s main claims and supporting evidence.",
            5: "Create a brief summary that captures the essence of the provided content.",
            6: "Summarize the main findings and conclusions from the given paragraphs.",
            7: "Write a summary that captures the central themes and concepts discussed in the text.",
            8: "Summarize the information, focusing on the most relevant details and omitting unnecessary elements.",
            9: "Condense the provided paragraphs into a clear and succinct summary.",
            10: "Craft a summary that effectively communicates the main points of the text in a concise manner.",
            11: "Summarize the text in simpler and easier-to-understand terms.",
            12: "Write a summary that highlights the practical implications of the given content.",
            13: "Create a summary that emphasizes the significance of the findings presented in the text.",
            14: "Provide a summary that addresses the potential limitations or weaknesses of the discussed research.",
            15: "Summarize the text, focusing on the methodology and research design used in the study.",
            16: "Craft a summary that presents the different perspectives or viewpoints expressed in the provided material.",
            17: "Summarize the text, emphasizing the connections and relationships between the various concepts discussed.",
            18: "Write a summary that outlines the main steps or procedures described in the text.",
            19: "Summarize the text, considering its implications for future research or practical applications.",
            20: "Come up with a summary that aligns with a specific word count requirement, such as [{word_count}] words.",
        },
        "conclusion": {
            1: "Synthesize the findings from different research sources to draw meaningful conclusions about [{topic}].",
            2: "Reflect on the significance of the study’s findings in addressing the research gap identified in the literature.",
            3: "Discuss the potential impact of the study’s findings on practical solutions or interventions in [{topic}].",
            4: "Address any limitations or constraints encountered during the study and their implications for the research outcomes.",
            5: "Highlight the implications of the study’s findings for future research directions and potential areas of exploration.",
            6: "Reflect on the methodology employed in the study and its strengths in generating reliable and valid results.",
            7: "Discuss the relevance of the study’s findings in the context of current theories or frameworks in [{topic}].",
            8: "Summarize the key arguments and findings of the study, highlighting their coherence and supporting evidence.",
            9: "Discuss any unexpected findings that emerged during the research process and their implications for understanding [{topic}].",
            10: "Reflect on the practical implications of the study’s findings for professionals or practitioners in [{topic}].",
            11: "Highlight the originality or unique contribution of the study’s findings to the existing body of knowledge in [{topic}].",
            12: "Discuss the broader implications of the study’s findings for relevant stakeholders or communities in [{topic}].",
            13: "Consider the broader societal impact of the study’s findings and their potential influence on policy-making or public awareness.",
            14: "Summarize the key recommendations derived from the study’s findings and their applicability in real-world contexts.",
            15: "Reflect on the significance of the research questions or hypotheses and their alignment with the study’s findings.",
            16: "Discuss any challenges or limitations encountered during the research process and their potential impact on the study’s outcomes.",
            17: "Highlight the practical value of the study’s findings for professionals or organizations in [{topic}].",
            18: "Reflect on the research process, including data collection, analysis, and interpretation, and the resulting insights.",
            19: "Discuss the implications of the study’s findings for academic debates and knowledge advancement in [{topic}].",
            20: "Conclude by reiterating the main findings and emphasizing their relevance and contributions to the field of [{topic}].",
        },
        "future_work": {
            1: "Provide recommendations for further research areas that can build upon the findings of the current study.",
            2: "Suggest potential avenues for future investigation and exploration related to the topic discussed.",
            3: "Identify three directions for future research that can contribute to expanding the knowledge in this field.",
            4: "Propose specific research questions that can be explored in future studies to advance the understanding of the topic.",
            5: "Discuss potential gaps in the current literature and propose areas where additional research is needed.",
            6: "Outline possible methodologies or approaches that can be employed in future studies to address unresolved questions.",
            7: "Highlight emerging trends or technologies that can be explored in future research to enhance the understanding of the topic.",
            8: "Suggest interdisciplinary collaborations or partnerships that can enrich future research endeavors in this field.",
            9: "Discuss the implications of the current study’s findings for practical applications and propose future work in that context.",
            10: "Provide suggestions for expanding the scope of future research to include different populations, contexts, or variables.",
        },
        "reference": {
            1: "Create a reference list following the APA style for the sources cited in your research paper on [{topic}].",
            2: "Compile a bibliography using the MLA format for the scholarly articles consulted in your study on [{topic}].",
            3: "Format the reference list in accordance with the Chicago Manual of Style for the sources referenced in your dissertation.",
            4: "Generate a list of references in the Harvard referencing style for the books, journals, and online sources cited in your literature review.",
            5: "Organize the reference list alphabetically by the author’s last name and chronologically by publication date for the sources used in your thesis.",
            6: "Ensure proper citation and referencing of primary and secondary sources in your annotated bibliography for the research conducted on [{topic}].",
        },
    },
    "ar": {
        "outline": {
            1: "قم بإنشاء مخطط تفصيلي لورقة أكاديمية استنادًا إلى جملة الموضوع المقدمة: قم بتطوير مخطط تفصيلي لورقة أكاديمية تتمحور حول جملة الموضوع: [{topic}]. حدد الأقسام الرئيسية والمواضيع الفرعية والنقاط الرئيسية التي سيتم تناولها مغطاة بالورقة.",
            2: "إنشاء مخطط تفصيلي شامل لمقالة بحثية حول الموضوع المحدد: إنشاء مخطط تفصيلي لمقال بحثي يركز على [{topic}]. قم ببناء المخطط التفصيلي ليشمل أقسامًا مثل المقدمة، ومراجعة الأدبيات، والمنهجية، والنتائج، والمناقشة ، والخاتمة.",
            3: "حدد الخطوط العريضة لعمل علمي حول جملة الموضوع المقدمة، بما في ذلك الأقسام الرئيسية والعناوين الفرعية: قدم مخططًا تفصيليًا لعمل علمي يتمحور حول جملة الموضوع: [{topic}]. حدد الأقسام الرئيسية والعناوين الفرعية والنقاط الداعمة التي يجب أن يتم تضمينه في العمل.",
            4: "قم بإنشاء مخطط تفصيلي لمقال صحفي يستكشف الجملة الموضوعية المحددة: ضع مخططًا تفصيليًا لمقالة صحفية تتعمق في [{topic}]. حدد الأقسام الرئيسية والمنهجية والإطار النظري والأدلة التجريبية والاستنتاجات التي سيتم طرحها الواردة في المقال.",
            5: "قم بإنشاء مخطط تفصيلي لورقة أكاديمية حول جملة الموضوع المقدمة، مع التركيز على التدفق المنطقي للأفكار: قم بصياغة مخطط تفصيلي لورقة أكاديمية تتناول [{topic}]. قم ببناء المخطط التفصيلي لضمان التدفق المنطقي للأفكار، بما في ذلك مقدمة، ومعلومات أساسية، والحجج الرئيسية، والأدلة الداعمة، وخاتمة موجزة.",
        },
        "introduction": {
            1: "صياغة مقدمة جذابة لورقة أكاديمية تدور حول موضوع البحث المقدم: 'قم بتطوير مقدمة تجذب انتباه القراء وتقدم لمحة موجزة عن موضوع البحث: [{topic}]. قدم أهمية البحث وسؤال البحث وأهداف الدراسة.'",
            2: "كتابة فقرة تمهيدية لعمل علمي يتناول الموضوع المعطى: 'أكتب فقرة تمهيدية تقدم القراء بفعالية للموضوع المتناول: [{topic}]. قدم معلومات خلفية وسياق والمبرر للبحث.'",
            3: "تطوير مقدمة لمقال أكاديمي يركز على الجملة الموضوعية المقدمة: 'أنشئ مقدمة تُعيد ترتيب مقال أكاديمي متمحور حول [{topic}]. حدد بوضوح مشكلة البحث ، وأبرز أهميتها ، وحدد هيكل المقال.'",
            4: "صياغة فقرة افتتاحية لورقة أكاديمية حول موضوع البحث المعطى: 'أكتب فقرة افتتاحية جذابة لورقة أكاديمية تتعامل مع [{topic}]. استخدم لغة جذابة لتقديم الموضوع ، ووضح أهميته ، ونقل أهداف البحث.'",
            5: "إنشاء مقدمة لدراسة بحثية تستكشف الجملة الموضوعية المقدمة: 'إنشاء مقدمة توفر نظرة شاملة على الدراسة البحثية المتعلقة بـ [{topic}]. قدم الفجوة البحثية ، وصف النهج الأساسي ، وأبرز المساهمات المتوقعة للدراسة.'",
            6: "تطوير مقدمة جذابة لعمل علمي على الموضوع المعطى: 'قم بتطوير مقدمة تجذب انتباه القراء وتقدم نظرة عامة على العمل العلمي المركز على [{topic}]. قدم السياق البحثي ، وحدد المواضيع الرئيسية ، وحدد أهداف البحث.'",
            7: "كتابة قسم تمهيدي لورقة أكاديمية تستكشف الجملة الموضوعية المقدمة: 'كتابة قسم تمهيدي يُعرِّف القراء على الموضوع الموجود في [{topic}]. قدم خلفية البحث ، وصف مشكلة البحث ، وحدد نطاق وغرض الدراسة.'",
            8: "صياغة بيان افتتاحي لمقال أكاديمي متمحور حول موضوع البحث المعطى: 'صياغة بيان افتتاحي يُقدِّم بفعالية مقالًا أكاديميًا مركزًا على [{topic}]. فاجئ القراء ببيان يثير التفكير وقدِّم لمحة موجزة عن منطق البحث.'",
            9: "تطوير مقدمة لعمل أكاديمي تسلط الضوء على أهمية الموضوع المعطى: 'قم بتطوير مقدمة تبرز أهمية وجدوى موضوع البحث: [{topic}]. ناقش أهميته في السياق الأوسع وحدد أهداف البحث والأهداف.'",
            10: "كتابة مقدمة جذابة لورقة أكاديمية تحدد السياق لموضوع البحث المعطى: 'كتابة مقدمة توضح سياق موضوع البحث: [{topic}]. قدِّم مجال الدراسة ، وقدِّم معلومات خلفية ذات صلة ، وصاغ مشكلة البحث والأهداف.'",
        },
        "review": {
            1: "إجراء استعراض أدبي حول موضوع [{TOPICSENTENCE}] ، ملخصًا للنتائج والتحليلات الرئيسية من الدراسات البحثية ذات الصلة.",
            2: "تحليل وتوليف الأدب الحالي حول [{TOPICSENTENCE}] ، محددًا النظريات والمفاهيم والطرق البحثية الرئيسية المستخدمة في الأبحاث السابقة.",
            3: "مراجعة مجموعة من المقالات العلمية حول [{TOPICSENTENCE}] ، مقيمًا بنقد منهجياتها ونقاط قوتها وضعفها.",
            4: "تحديد ومناقشة المواضيع والاتجاهات الرئيسية التي تظهر من الأدب حول [{TOPICSENTENCE}] ، مسلطًا الضوء على مناطق التوافق والجدل.",
            5: "إجراء استعراض أدبي منهجي حول [{TOPICSENTENCE}] ، ينظم ويصنف الأوراق البحثية ذات الصلة بناءً على أسئلتها البحثية وطرقها والنتائج.",
            6: "تقديم لمحة عن الأطُرَ النظرية والنماذج المفاهيمية التي تم استخدامها في الأدب حول [{TOPICSENTENCE}].",
            7: "تحليل الفجوات والقيود في الأدب الحالي حول [{TOPICSENTENCE}] ، مقترحًا مجالات للبحث والاستكشاف الإضافي.",
            8: "مقارنة وتناقش النتائج والاستنتاجات من دراسات البحث المختلفة حول [{TOPICSENTENCE}] ، مسلطًا الضوء على التباينات والتناقضات.",
            9: "فحص تأثير وآثار النتائج البحثية في الأدب حول [{TOPICSENTENCE}] ، مراعاة صلوحيتها وقابليتها للتطبيق.",
            10: "ناقش النهج المنهجي المستخدم في الأدب حول [{TOPICSENTENCE}] ، مقيمًا فعاليته في التعامل مع أسئلة البحث.",
            11: "تحديد الباحثين والعلماء الرئيسيين الذين قدموا إسهامات كبيرة في مجال [{TOPICSENTENCE}] ، مستشهدًا بأعمالهم المؤثرة.",
            12: "ملخص ونقد النهج المستخدمة في الأدب حول [{TOPICSENTENCE}] ، مقيمًا نقاط قوتها وضعفها.",
            13: "تحليل تصميم البحث وطرق جمع البيانات المستخدمة في الأدب حول [{TOPICSENTENCE}] ، مقيمًا ملائمتها وموثوقيتها.",
            14: "تقديم تقييم نقدي لجودة وصرامة الدراسات البحثية المراجعة في الأدب حول [{TOPICSENTENCE}] .",
            15: "ناقش الآثار النظرية والعملية لنتائج البحث في الأدب حول [{TOPICSENTENCE}] ، مع مراعاة أهميتها في الميدان.",
            16: "توليف النتائج والاستنتاجات الرئيسية من الأدب المراجع حول [{TOPICSENTENCE}] ، مسلطًا الضوء على الفجوات ومجالات البحث المستقبلية.",
            17: "ناقش القيود والتحديات التي واجهت دراسات البحث المراجعة حول [{TOPICSENTENCE}] ، مقترحًا استراتيجيات للتحسين.",
            18: "قيمة الإشارة والصدقية للمصادر المستخدمة في الأدب حول [{TOPICSENTENCE}] ، مع ضمان تضمين أوراق بحثية عالية الجودة وذات سمعة طيبة.",
            19: "تقديم قائمة مرجعية شاملة لورق المراجعة والدراسات البحثية المدرجة في استعراض الأدب حول [{TOPICSENTENCE}] .",
            20: "خُلِص على المساهمات الرئيسية والرؤى من الأدب المراجع حول [{TOPICSENTENCE}]، مبرزًا أهميتها في تقدم المعرفة في هذا المجال.",
        },
        "methodology": {
            1: "قم بتصميم منهج بحث لاستكشاف العلاقة بين [المتغيرات] في سياق [{topic}].",
            2: "وضّح أهداف البحث بوضوح وقم بوضع منهج شامل لتحقيق تلك الأهداف في سياق [{topic}].",
            3: "اكتب قسمًا مفصلًا حول المنهج لإجراء دراسة نوعية حول [{topic}].",
            4: "صمم استبيانًا وصف تقنية العينة التي ستُستخدم في دراسة بحثية كمية حول [{topic}].",
            5: "ناقش قوة وضعف استخدام نهج الأساليب المختلطة في دراسة [{topic}].",
            6: "اقترح تصميم بحث ومنهجية لإجراء دراسة تجريبية حول [{topic}].",
            7: "حدد منهج استعراض نظامي لتحليل وتوليف الأدب الحالي حول [{topic}].",
            8: "قم بتحليل قوة وضعف المنهج البحثي المختار في استكشاف [{topic}].",
            9: "وضّح إجراءات خطوة بخطوة لجمع وتحليل البيانات الأساسية حول [{topic}].",
            10: "قيّم ملاءمة استخدام منهج دراسة الحالة لاستكشاف [{topic}].",
            11: "صمم منهج بحث لإجراء مقابلات مع أصحاب المصلحة الرئيسيين في مجال [{topic}].",
            12: "ناقش الاعتبارات الأخلاقية التي يجب معالجتها عند تنفيذ المنهج البحثي المقترح لـ [{topic}].",
            13: "أنشئ خطة لجمع البيانات وصف تقنيات تحليل البيانات التي ستُستخدم في دراسة بحثية كمية حول [{topic}].",
            14: "برّر اختيار تصميم بحث ومنهجية معينة لاستكشاف [{topic}] استنادًا إلى ملاءمتها وجدواها.",
            15: "ناقش التحيزات المحتملة والقيود المرتبطة بالمنهج البحثي المختار في دراسة [{topic}].",
            16: "قم بتطوير إطار لتحليل البيانات النوعية التي تم جمعها من خلال المقابلات أو مجموعات التركيز أو الملاحظات حول [{topic}].",
            17: "صف الخطوات المشاركة في إجراء استعراض أدبي نظامي كجزء من المنهج البحثي حول [{topic}].",
            18: "قيّم موثوقية وصدق الأدوات القياس المختارة في المنهج البحثي حول [{topic}].",
            19: "شرح كيفية معالجة منهجية البحث للمتغيرات الزائفة المحتملة وضمان الصدق الداخلي في دراسة [{topic}].",
            20: "قارن وقارن بين منهجيات البحث المختلفة (مثل التجريبية، الاستبيان، دراسة الحالة) من حيث ملاءمتها لاستكشاف [{topic}].",
        },
        "discussion": {
            1: "قيّم أهمية نتائج الدراسة وتداولاتها لتقدم الفهم حول [{topic}].",
            2: "ناقش مساهمات الدراسة الحالية في الجسم الحالي للمعرفة حول [{topic}] وأبرز المجالات المستقبلية للبحث.",
            3: "ناقش كيفية توافق نتائج الدراسة أو تحديها للنظريات والنماذج الحالية في ميدان [{topic}].",
            4: "انعكس على الاختيارات المنهجية التي تم اتخاذها في الدراسة وقيم قوتها وضعفها بالنسبة لأهداف البحث.",
            5: "قارن نتائج الدراسة الحالية بالأبحاث السابقة في الأدب، مبرزًا الشبه والاختلافات والأسباب المحتملة للتناقضات.",
            6: "ناقش أي نتائج غير متوقعة أو متناقضة واقترح تفسيرات محتملة أو طرق لمزيد من البحث.",
            7: "فحص التداولات العملية لنتائج الدراسة وناقش كيف يمكن أن تؤثر في اتخاذ القرارات أو الممارسة في مجال [{topic}].",
            8: "نظر في إمكانية تعميم نتائج الدراسة إلى سياقات أو سكان أخرى وناقش الأثر المحتمل على المعرفة الأوسع في مجال [{topic}].",
            9: "ناقش الاعتبارات الأخلاقية المشاركة في إجراء الدراسة وتأثيرها على تفسير وتعميم النتائج.",
            10: "قم بتلخيص النتائج الرئيسية للدراسة، مؤكدًا أهميتها وقيودها وتداعياتها على مستقبل البحث والممارسة في مجال [{topic}].",
        },
        "result": {
            1: "قدم وقم بتفسير البيانات الكمية المجمعة في الدراسة لتوفير تحليل شامل للنتائج المتعلقة بـ [{topic}].",
            2: "صف الأنماط والاتجاهات الرئيسية الملاحظة في البيانات النوعية التي تم جمعها أثناء البحث حول [{topic}].",
            3: "قم بتحليل الأهمية الإحصائية للنتائج التي تم الحصول عليها من التجارب المجراة حول [{topic}].",
            4: "قدم استجابات الاستطلاع وخلاصة السمات والتحليلات الرئيسية المستمدة من البيانات المتعلقة بـ [{topic}].",
            5: "ناقش العلاقات والارتباطات التي تم العثور عليها بين المتغيرات المدروسة في الدراسة حول [{topic}]. وتوضيح النتائج الرئيسية للبحث من خلال جداول واضحة وموجزة،",
            6: "قم بتفسير نتائج تحليل البيانات وناقش تداولاتها لميدان [{topic}].",
            7: "حيِّر النتائج الرئيسية للبحث من خلال جداول ورسوم بيانية ورسوم بيانية واضحة وموجزة حول [{topic}].",
            8: "ناقش أي نتائج غير متوقعة أو متناقضة تم الحصول عليها خلال الدراسة واقترح تفسيرات محتملة لها.",
            9: "قارن وقارن بين نتائج الدراسة الحالية والأدب الحالي المتاح حول [{topic}].",
            10: "أبرز الأهمية الإحصائية للفروق أو التشابه الملاحظ بين المجموعات التجريبية في الدراسة حول [{topic}].",
            11: "قم بتلخيص الاستجابات النوعية التي تم الحصول عليها من المقابلات أو أسئلة الاستطلاع المفتوحة وحدد المواضيع المتكررة.",
            12: "ناقش قيود الدراسة من حيث التحيزات المحتملة أو العوامل المرافقة التي قد تكون قد أثرت على النتائج بالنسبة لـ [{topic}].",
            13: "قدم تحليلًا مفصلًا للبيانات المجمعة لدعم الادعاءات المقدمة في الدراسة حول [{topic}].",
            14: "فسّر نتائج الاختبارات الإحصائية التي تم إجراؤها لتقييم الفروض المصاغة لـ [{topic}].",
            15: "ناقش أي نتائج غير متوقعة أو أنماط ظهرت من التحليل وتداعياتها على البحث المستقبلي.",
            16: "قدم الإحصائيات الوصفية ومقاييس الاتجاه المركزي والتباين للمتغيرات المدروسة في الدراسة حول [{topic}].",
            17: "ناقش موثوقية وصدق القياسات المستخدمة في الدراسة لضمان دقة النتائج بالنسبة لـ [{topic}].",
            18: "قم بتلخيص النتائج الرئيسية وأهميتها في تحقيق أهداف البحث حول [{topic}].",
            19: "قدم تحليلًا مفصلًا للبيانات المجمعة لدعم الادعاءات المقدمة في الدراسة حول [{topic}].",
            20: "فسّر نتائج تحليل البيانات في ضوء الأسئلة والأهداف البحثية المصاغة لـ [{topic}].",
        },
        "summary": {
            1: "خُلِص على المحتوى المُقدَّم في الفقرات التالية.",
            2: "قدم ملخصًا موجزًا للنقاط الرئيسية المناقشة في النص.",
            3: "اختصر الأفكار والحجج الرئيسية المقدمة في المادة المعطاة.",
            4: "خُلِص النص، مبرزًا الادعاءات الرئيسية للكاتب والأدلة الداعمة.",
            5: "أنشئ ملخصًا موجزًا يلتقط جوهر المحتوى المُقدَّم.",
            6: "خُلِص النتائج والاستنتاجات الرئيسية من الفقرات المعطاة.",
            7: "اكتب ملخصًا يلتقط المواضيع والمفاهيم المركزية المناقشة في النص.",
            8: "خُلِص المعلومات، مركزًا على التفاصيل الأكثر صلة وحذف العناصر الغير ضرورية.",
            9: "اختصر الفقرات المقدمة إلى ملخص واضح وموجز.",
            10: "صاغ ملخصًا ينقل بفعالية النقاط الرئيسية للنص بطريقة موجزة.",
            11: "خُلِص النص بمصطلحات أبسط وأسهل فهمًا.",
            12: "اكتب ملخصًا يبرز النتائج العملية للمحتوى المعطى.",
            13: "أنشئ ملخصًا يؤكد على أهمية النتائج المقدمة في النص.",
            14: "قدم ملخصًا يتناول القيود أو الضعف المحتملة للأبحاث المناقشة.",
            15: "خُلِص النص، مركزًا على الأسلوب البحثي وتصميم الدراسة المستخدم فيها.",
            16: "صاغ ملخصًا يقدم وجهات النظر المختلفة المعبر عنها في المادة المقدمة.",
            17: "خُلِص النص، مؤكدًا على العلاقات والتصالب بين المفاهيم المختلفة المناقشة.",
            18: "اكتب ملخصًا يوضح الخطوات أو الإجراءات الرئيسية الموجودة في النص.",
            19: "خُلِص النص، مأخوذًا في اعتبارك تأثيره على الأبحاث المستقبلية أو التطبيقات العملية.",
            20: "أتتناسب مع متطلبات عدد معين من الكلمات، مثل [{word_count}] كلمة.",
        },
        "conclusion": {
            1: "توليف النتائج من مصادر بحث مختلفة لاستخلاص استنتاجات ذات مغزى حول [{topic}].",
            2: "تأمل في أهمية نتائج الدراسة في التعامل مع الفجوة البحثية المحددة في الأدب.",
            3: "ناقش الأثر المحتمل لنتائج الدراسة على الحلول العملية أو التدخلات في [{topic}].",
            4: "تناول أي قيود أو قيود واجهتها الدراسة وتأثيرها على نتائج البحث.",
            5: "أبرز تأثيرات نتائج الدراسة على اتجاهات البحث المستقبلية والمجالات المحتملة للاستكشاف.",
            6: "تأمل في الطريقة المستخدمة في الدراسة وقوتها في إنتاج نتائج قائمة وصحيحة.",
            7: "ناقش أهمية نتائج الدراسة في سياق النظريات أو الأطُر الحالية في [{topic}].",
            8: "خُلِص الحجج والنتائج الرئيسية للدراسة، مبرزًا تناغمها والأدلة الداعمة لها.",
            9: "ناقش أي نتائج غير متوقعة ظهرت خلال عملية البحث وتأثيرها على فهم [{topic}].",
            10: "تأمل في الآثار العملية لنتائج الدراسة على المحترفين أو الممارسين في [{topic}].",
            11: "أبرز الأصالة أو الإسهام الفريد لنتائج الدراسة للمساهمة في الجسم المعرفي الحالي في [{topic}].",
            12: "ناقش الآثار الأوسع لنتائج الدراسة على الجهات المعنية أو المجتمعات في [{topic}].",
            13: "اعتبر الأثر الاجتماعي الأوسع لنتائج الدراسة وتأثيرها المحتمل على صنع السياسات أو التوعية العامة.",
            14: "خُلِص التوصيات الرئيسية المستمدة من نتائج الدراسة وقابليتها للتطبيق في سياقات الواقع.",
            15: "تأمل في أهمية الأسئلة البحثية أو الفرضيات وتوافقها مع نتائج الدراسة.",
            16: "ناقش أي تحديات أو قيود واجهتها عملية البحث وتأثيرها المحتمل على نتائج الدراسة.",
            17: "أبرز القيمة العملية لنتائج الدراسة للمحترفين أو المنظمات في [{topic}].",
            18: "تأمل في عملية البحث، بما في ذلك جمع البيانات والتحليل والتفسير، والتفاصيل الناتجة عنها.",
            19: "ناقش آثار نتائج الدراسة على النقاشات الأكاديمية وتقدم المعرفة في [{topic}].",
            20: "اختتم بإعادة تأكيد النتائج الرئيسية وتأكيد أهميتها وإسهاماتها في مجال [{topic}].",
        },
        "future_work": {
            1: "قدم توصيات لمجالات البحث الأخرى التي يمكن البناء عليها استنادًا إلى نتائج الدراسة الحالية.",
            2: "اقترح طرقًا محتملة للاستكشاف والتحقيق المستقبلي المتعلقة بالموضوع المناقش.",
            3: "حدد ثلاثة اتجاهات للبحث المستقبلي يمكن أن تسهم في توسيع المعرفة في هذا المجال.",
            4: "اقترح أسئلة بحث محددة يمكن استكشافها في الدراسات المستقبلية لتقدم الفهم للموضوع.",
            5: "ناقش الفجوات المحتملة في الأدب الحالي واقترح مجالات تحتاج إلى بحث إضافي.",
            6: "صاغ منهجيات أو نهجًا ممكنة يمكن توظيفها في الدراسات المستقبلية للتعامل مع أسئلة لم يتم حلها بعد.",
            7: "أبرز الاتجاهات أو التقنيات الناشئة التي يمكن استكشافها في البحث المستقبل لتعزيز فهم الموضوع.",
            8: "اقترح تعاونًا متعدد التخصصات أو شراكات يمكن أن تثري الجهود البحثية المستقبلية في هذا المجال.",
            9: "ناقش آثار نتائج الدراسة الحالية على التطبيقات العملية واقترح أعمالًا مستقبلية في هذا السياق.",
            10: "قدم اقتراحات لتوسيع نطاق البحث المستقبل لتشمل فئات سكانية مختلفة أو سياقات أو متغيرات مختلفة.",
        },
        "reference": {
            1: "أنشئ قائمة مراجع وفقًا لأسلوب APA للمصادر المستشهدة في بحثك العلمي حول [{topic}].",
            2: "قم بتجميع قائمة مراجع باستخدام تنسيق MLA للمقالات العلمية المستشار بها في دراستك حول [{topic}].",
            3: "قم بتنسيق قائمة المراجع وفقًا لدليل شيكاغو للأسلوب للمصادر المرجعة في أطروحتك.",
            4: "أنشئ قائمة بالمراجع بأسلوب الهارفارد للكتب والمجلات والمصادر عبر الإنترنت المستشهد بها في استعراض الأدب الخاص بك.",
            5: "نظم قائمة المراجع ترتيبها ترتيبًا ألفبيًا حسب اسم الكاتب وتاريخ النشر للمصادر المستخدمة في رسالتك.",
            6: "تأكد من الاقتباس والإشارة السليمة للمصادر الأولية والثانوية في قائمة مراجعك التوضيحية للبحث الذي أُجري حول [{topic}].",
        },
    },
}


warning = {
    "en": " Note: (Start your answering directly without welcome, warning, notes, or warning or word sure. I just want to answer the question, without any side talk)",
    "ar": " ملاحظة: (إبدا بالإجابة مباشرة بدون ترحيب أو تحذير أو ملاحظات ، أو تنبيه، أريد الإجابة عن السؤال فقط ، بدون إي كلام جانبي)",
}


def get_step_research(lang):
    step_research = {
        "introduction": research_prompt[lang]["introduction"].get(8, 8) + warning[lang],
        "methodology": research_prompt[lang]["methodology"].get(19, 19) + warning[lang],
        "discussion": research_prompt[lang]["discussion"].get(10, 10) + warning[lang],
        "summary": research_prompt[lang]["summary"].get(5, 5) + warning[lang],
        "result": research_prompt[lang]["result"].get(5, 5) + warning[lang],
        "conclusion": research_prompt[lang]["conclusion"].get(8, 8) + warning[lang],
        "future_work": research_prompt[lang]["future_work"].get(9, 9) + warning[lang],
        "references": research_prompt[lang]["reference"].get(1, 1) + warning[lang],
    }
    return step_research


def get_title(key, lang="en"):
    step_tran = {
        "en": {
            "introduction": "Introduction",
            "methodology": "Methodology",
            "discussion": "Discussion",
            "summary": "Summary",
            "result": "Result",
            "future_work": "Future Work",
            "conclusion": "Conclusion",
            "references": "References",
        },
        "ar": {
            "introduction": "المقدمة",
            "methodology": "المنهجية",
            "discussion": "المناقشة",
            "summary": "الملخص",
            "result": "النتائج",
            "future_work": "الأعمال المستقبلية",
            "conclusion": "الخاتمة",
            "references": "المراجع",
        },
    }

    # Ensure the provided language is in lowercase
    lang = lang.lower()

    # If the language and key are present, return the translated title
    if lang in step_tran and key in step_tran[lang]:
        return step_tran[lang][key]
    else:
        # Return a default value or handle the case when the language or key is not found
        return "Translation not available"
